package com.endocrine.checkin.domain.usecase

import assertk.assertThat
import assertk.assertions.isBetween
import assertk.assertions.isEqualTo
import assertk.assertions.isGreaterThan
import com.endocrine.checkin.domain.model.BodyState
import com.endocrine.checkin.domain.model.CheckinEntry
import com.endocrine.checkin.domain.model.Emotion
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import java.util.TimeZone

class SaveCheckinUseCaseTest {

    private val repo = FakeCheckinRepository()
    private val saveCheckin = SaveCheckinUseCase(repo)

    private fun newEntry(
        id: Long = 0,
        timestamp: Long = 0,
        timezone: String = "",
        note: String? = null,
    ) = CheckinEntry(
        id = id,
        timestamp = timestamp,
        timezone = timezone,
        body = BodyState(3, 3, 3, 3),
        emotion = Emotion("Freude", "glücklich", "erfreut"),
        note = note,
    )

    @Test
    fun `a new entry is stamped with now and the system zone`() = runTest {
        val before = System.currentTimeMillis()
        val id = saveCheckin(newEntry())
        val after = System.currentTimeMillis()

        val stored = repo.getById(id)!!
        assertThat(stored.timestamp).isBetween(before, after)
        assertThat(stored.timezone).isEqualTo(TimeZone.getDefault().id)
    }

    @Test
    fun `editing an existing entry preserves its original timestamp and zone`() = runTest {
        val original = newEntry(timestamp = 12_345L, timezone = "Europe/Berlin")
        val id = saveCheckin(original.copy(id = 0)).also { /* id assigned */ }
        val saved = repo.getById(id)!!

        // Re-save the same row with a changed note; id != 0 → must NOT re-stamp.
        val edited = saved.copy(note = "geändert")
        saveCheckin(edited)

        val result = repo.getById(id)!!
        assertThat(result.note).isEqualTo("geändert")
        assertThat(result.timestamp).isEqualTo(saved.timestamp)
        assertThat(result.timezone).isEqualTo(saved.timezone)
    }

    @Test
    fun `editing reuses the same id and does not create a second row`() = runTest {
        val id = saveCheckin(newEntry())
        saveCheckin(repo.getById(id)!!.copy(note = "x"))
        assertThat(repo.saved.size).isEqualTo(1)
    }

    @Test
    fun `new entries get distinct autogenerated ids`() = runTest {
        val id1 = saveCheckin(newEntry())
        val id2 = saveCheckin(newEntry())
        assertThat(id2).isGreaterThan(id1)
        assertThat(repo.saved.size).isEqualTo(2)
    }
}
